// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kztelbnarzrpbjlqastg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6dGVsYm5hcnpycGJqbHFhc3RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjcxNjEsImV4cCI6MjA2NDYwMzE2MX0.0jdEKfZgKsAqmZUWhhFqhZMWXYK-R8AABzwEQMgGjvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);